variables:
  RESULTS: results
  CALCULATOR: calculator
  MAX_LINE_LENGTH: 127
  CODE_STYLE: $(RESULTS)/code_style

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage:
  jobs:

  - job:
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
      displayName: Use Python 3.6

    - script: |
        python -m pip install --upgrade pip
        pip install -r $(CALCULATOR)/requirements.txt
      displayName: 'Install dependencies'

    - bash: |
        pwd
        mkdir -p $(CODE_STYLE)
      displayName: 'Make results directory'

    - script: |
        flake8 . --count --select=E431 --max-line-length $(MAX_LINE_LENGTH) --show-source --statistics --benchmark --output-file=$(CODE_STYLE)/flake8_style_check.log --tee
      displayName: 'Flake8 style check'

    - publish: $(CODE_STYLE)
      artifact: Flake8
      displayName: 'Publish artifact'